// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmsrbcrkuijsqlabynhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imttc3JiY3JrdWlqc3FsYWJ5bmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxNjA3NjIsImV4cCI6MjA4NDczNjc2Mn0.GYs1iBpbn35w_zBakt8oFCZqaLsSAE4PpbwCJ4TtbnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});