// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbohvgcssebtqvednywr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ib2h2Z2Nzc2VidHF2ZWRueXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNzI4NzYsImV4cCI6MjA1NDk0ODg3Nn0.bloUiEVMnlyPtevZItiLq1ZrMnibpcPtGnMSITg7QIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);